### PR TITLE
fix issue 5: mocha dependencies -> devDependencies

### PR DESCRIPTION
**Pull request by xgbuils**
fixed issue https://github.com/mcandre/node-range/issues/5

And please, update npm package. I get an old version when installing with npm.

### CODE REVIEW

**Comment by mcandre** [comment]
Thanks for contributing!

Could you also remove `mocha` from the regular dependency list?

**Comment by xgbuils** [comment]
Sorry, I had an oversight. I amended this: https://github.com/xgbuils/node-range/commit/18b4e4661a44ad51fccc97b3b3e2f992f737d54c

**Comment by mcandre** [comment]
Cheers!

**Comment by mcandre** [comment]
:P Hit the wrong button!

**Pull request merged**
