### PR TITLE
Fix issue 7 (annoying for's almost identical.)

### PR DESCRIPTION
**Pull request by xgbuils**
Here you go! :)

### CODE REVIEW

**Comment by mcandre** [comment]
I understand what minified/uglified code is, but why include it in `dist/`? Is this an NPM habit, or perhaps a Bower habit?

**Comment by xgbuils** [comment]
wow! good question. I would not know why. I did it for imitation. Many projects place in dist/ (distribution) or build/ folder code built by a task runner. [jQuery](https://www.npmjs.com/package/jquery) is an example.

**Comment by mcandre** [comment]
Hmm, that makes some sense.

In the future, I'd like `dist/` kept outside of version control. NPM does a find job making node-range available for backend developers, and we can publish a [Bower](http://bower.io/) package for frontend developers.

**Comment by xgbuils** [comment]
I don't understand it. It's already done what you like. Currently `dist/` is kept outside of version control: [.gitignore dist/](https://github.com/mcandre/node-range/blob/e96c631fde0ad8f55aca029abb652490d72cb2d0/.gitignore#L2).

**Comment by mcandre** [comment]
Thank you.

**Pull request merged**
